[paths]
tm_snapshots_dir = ""
borg_repo = ""
home_dir = ""

[backup]
encryption = "none"
include_patterns = ["**/*"]
exclude_patterns = [
    "**/Library", "*.tmp", "*.iso", "*.vdi", "*.vmdk", "*.ova",
    "*.vbox", "*.img", "*.dmg", "**/node_modules/*", "**/.git/*", "**/build/*"
]

[test]
test_snapshots_dir = ".testsnaps"
